baseURL = 'https://inporra.com'
languageCode = 'id-ID'
title = 'InpoRRA'
theme = 'blog'
enableRobotsTXT = 'true'
paginate = 11
summaryLength = 43

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[params]
  author = 'Rizqy'
  Description = 'Berbagi Info menarik seputar Internet, Teknologi, Budaya, Traveling, dan Info menarik lainnya.'
  favicon = 'https://img.icons8.com/external-tanah-basah-basic-outline-tanah-basah/512/202124/external-health-sport-tanah-basah-basic-outline-tanah-basah.png'
  twitter = 'Rizqy'

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 5
    ordered = false
[markup.goldmark.renderer]
  unsafe = true
[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "keywords"
    weight = 80
  [[related.indices]]
    name = "title"
    weight = 70